version: 0.2


env:
  variables:
    ECR_REPO_NAME: "be-sb-app"
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "443370714870"
    CONTAINER_NAME: "be-sb-01"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Buildx...
      - mkdir -p ~/.docker/cli-plugins
      - curl -sSL https://github.com/docker/buildx/releases/download/v0.11.2/buildx-v0.11.2.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
      - chmod +x ~/.docker/cli-plugins/docker-buildx
      - docker buildx version

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - echo Creating buildx builder...
      - docker buildx create --use || docker buildx use mybuilder  # ✅ create builder

  build:
    commands:
      - echo "Building the application..."
      - mvn clean package
      - echo Building the Docker image...
      #- docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
      - docker buildx build --platform linux/amd64 -t $IMAGE_URI . --push
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - aws ecr batch-delete-image --repository-name $ECR_REPO_NAME --image-ids imageTag=$IMAGE_TAG || true
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - echo Build completed on `date`
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$IMAGE_URI" > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json